import '@radix-ui/themes/styles.css';
import './theme-config.css';
import NavBar from './NavBar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Theme, ThemePanel, Container } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider';

// radix-ui theme -> css 컴포넌트가 구성되어 편함
// 해당 페이지에서 선언하고 전역으로 사용

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
// nextjs 프로젝트는 기본적으로 인터 폰트를 사용
// 하지만, radix-ui에서는 인터 폰트를 사용하지 않음

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.variable}>
                {/** 전역으로 radix의 theme 컴포넌트 설정 */}
                <QueryClientProvider>
                    <AuthProvider>
                        <Theme>
                            <NavBar />
                            <main className="p-5">
                                <Container> {children} </Container>
                            </main>
                            {/* <ThemePanel /> 
                     -> 테마 패널 이용시 사용자 화면에서 테마 변경을 볼 수 있음
                    */}
                        </Theme>
                    </AuthProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
